apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sdk-datastore-storagemanager-service
  description: StorageManager Service of the Superb Data Kraken
  annotations:
    dev.azure.com/project-repo: EFS-SDK/storage-manager
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - spring-boot
    - sdk
    - sdk-datastore
  links:
    - url: https://sdk.efs.ai/storagemanager/swagger-ui/index.html
      title: e:fs SDK (prod) Swagger UI
    - url: https://sdk-dev.efs.ai/storagemanager/swagger-ui/index.html
      title: e:fs SDK (dev) Swagger UI
    - url: https://aicloud.efs.ai/storagemanager/swagger-ui/index.html
      title: AICloud (prod) Swagger UI
spec:
  type: service
  lifecycle: production
  owner: team-sdk
  system: sdk
  subcomponentOf: sdk-datastore
  dependsOn:
    - component:sdk-operations-keycloak-service
    - component:sdk-commons
  providesApis:
    - sdk-datastore-storagemanager-api
  consumesApis:
    - sdk-operations-keycloak-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sdk-datastore-storagemanager-api
  description: StorageManager API of the Superb Data Kraken
  annotations:
    dev.azure.com/project-repo: EFS-SDK/storage-manager
  tags:
    - sdk
    - sdk-datastore
  links:
    - url: https://sdk.efs.ai/storagemanager/swagger-ui/index.html
      title: e:fs SDK (prod) Swagger UI
    - url: https://sdk-dev.efs.ai/storagemanager/swagger-ui/index.html
      title: e:fs SDK (dev) Swagger UI
    - url: https://aicloud.efs.ai/storagemanager/swagger-ui/index.html
      title: AICloud (prod) Swagger UI
spec:
  type: openapi
  lifecycle: production
  owner: team-sdk
  system: sdk
  definition:
    $text: https://sdk.efs.ai/storagemanager/v3/api-docs