site_name: StorageManager
repo_url: https://dev.azure.com/EFSCIS/EFS-SDK/_git/storage-manager
site_description: Documentation for the StorageManager service of the Superb Data Kraken

nav:
  - Home: index.md
  - Architecture Decision Records (ADR):
    - Template: arch/0000_template-adr.md
    - ADR-0001: arch/0001_support-s3-storage.md

plugins:
  - techdocs-core