apidoc:
  title: SDK StorageManager-API
sdk:
  oauth2:
    config-url: https://$(DOMAIN)/auth/realms/$(REALM)/.well-known/openid-configuration
    client-id: sdk-client
    authorization-grant-type: authorization_code
    scope: openid
    user-name-attribute: preferred_username
management:
  endpoints:
    web:
      exposure:
        include: [ prometheus, health, info ]
server:
  port: 8090
  servlet:
    context-path: /storagemanager
storagemanager:
  storage:
    # using Azure Blob storage:
    azure:
      cors:
        origins: $(DOMAIN)
        maxAge: 60
      region: westeurope
      resourcegroup: SDK
      # these are the default settings in the azure storage client and don't have to be explicitly set
      storage-account-default-settings:
        soft-delete-blobs-enabled: true
        retention-time-deleted-blobs: 14
        soft-delete-containers-enabled: true
        retention-time-deleted-containers: 14
        versioning-blobs-enabled: true
        blob-versions-until-cool-tier-days: 1
        blob-versions-until-archive-tier-days: 2
        blob-versions-until-delete-days: 14
      user:
        client-id: <client-id>
        client-secret: <client-secret>
        tenant: <tenant>
    #  # using S3 storage:
    #  s3:
    #   endpoint: storage.sdk.example.com
    #   accessKey: <S3_ACCESS_KEY>
    #   secretKey: <S3_SECRET_KEY>
    #   bucketName: sdk-storage
