apiVersion: v1
kind: ServiceAccount
metadata:
 name: storagemanager-account
 namespace: operations
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storagemanager-namespace-reader-binding
  namespace: operations
subjects:
  - kind: ServiceAccount
    name: storagemanager-account
    namespace: operations
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: namespace-reader
  apiGroup: ""