apiVersion: v1
kind: Secret
stringData:
  storagemanager.storage.azure.user.client-id: $(AZURE_STORAGE_CLIENT_ID)
  storagemanager.storage.azure.user.client-secret: $(AZURE_STORAGE_CLIENT_SECRET)
  storagemanager.storage.azure.user.tenant: $(AZURE_TENANT_ID)
  storagemanager.auth.cliend-id: $(AUTH_CLIENT_ID)
  storagemanager.auth.client-secret: $(AUTH_CLIENT_SECRET)
metadata:
  name: storagemanager-secret
  namespace: operations
type: Opaque